packages:
  - 'apps/*'
  - 'packages/*'
  - 'packages/config/*'

catalog:
  # React ecosystem
  react: ^18.2.0
  react-dom: ^18.2.0
  react-native: 0.73.4
  next: ^14.0.4
  
  # TypeScript
  typescript: ^5.3.3
  '@types/react': ^18.2.45
  '@types/react-dom': ^18.2.18
  '@types/node': ^20.10.5
  
  # Testing
  jest: ^29.7.0
  '@testing-library/react': ^14.1.2
  '@testing-library/react-native': ^12.4.3
  '@testing-library/jest-dom': ^6.1.6
  '@playwright/test': ^1.40.1
  supertest: ^6.3.3
  
  # Linting and formatting
  eslint: ^8.56.0
  prettier: ^3.1.1
  
  # Database
  mongodb: ^6.3.0
  redis: ^4.6.12
  elasticsearch: ^8.11.0
  
  # Blockchain
  ethers: ^6.9.2
  hardhat: ^2.19.4
  '@nomicfoundation/hardhat-toolbox': ^4.0.0
  
  # Utilities
  lodash: ^4.17.21
  dayjs: ^1.11.10
  zod: ^3.22.4
